/**
 * Represents an AI Agent configuration.
 */
export interface AIAgent {
  id: string; // Unique identifier for the agent (e.g., UUID from Supabase)
  name: string; // User-defined name for the agent
  prompt: string; // The system prompt defining the agent's behavior
  knowledge_document_ids?: string[]; // Optional array of knowledge document IDs linked to this agent
  created_at: string; // Timestamp of creation
  updated_at: string; // Timestamp of last update
  // Add any other relevant fields as needed, e.g., user_id, organization_id
}

/**
 * Type for creating a new AI Agent (omits fields generated by the backend).
 */
export type NewAIAgent = Omit<AIAgent, 'id' | 'created_at' | 'updated_at'>;

/**
 * Type for updating an existing AI Agent (makes most fields optional).
 */
export type UpdateAIAgent = Partial<Omit<AIAgent, 'id' | 'created_at'>>;
